# Generated by Django 3.2.7 on 2021-10-01 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='game',
            name='odds',
            field=models.FloatField(default=1.0, max_length=20),
        ),
    ]
