# Generated by Django 3.2.7 on 2021-10-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='membership',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
