# Generated by Django 3.2.7 on 2021-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211005_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
