# Generated by Django 3.2.7 on 2021-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_group_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
