# Generated by Django 3.2.7 on 2021-10-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_group_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
