# Generated by Django 3.2.7 on 2021-10-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.group'),
        ),
    ]
