# Generated by Django 3.2.7 on 2021-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_paymenttransaction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
