# Generated by Django 3.2.7 on 2021-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_group_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
