# Generated by Django 3.2.7 on 2021-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211014_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='odds',
            field=models.CharField(default=14, max_length=100),
        ),
    ]
