# Generated by Django 3.2.7 on 2021-10-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_group_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Phone Number'),
        ),
    ]
