# Generated by Django 3.2.7 on 2021-10-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='number',
            new_name='number_of_games',
        ),
    ]
